modLoader="javafml"
loaderVersion="[36,)"
license="MIT License"
#logoFile="materialis_logo.png"
issueTrackerURL="https://github.com/RCXcrafter/Materialis/issues"

[[mods]]
modId="materialis"
version="${file.jarVersion}"
displayName="Materialis"
#updateJSONURL="https://change.me.example.invalid/updates.json"
displayURL="https://www.curseforge.com/minecraft/mc-mods/materialis"
logoFile="logo.png"
#credits=""
authors="RCXcrafter"
description='''
Materialis is an addon for Tinkers Construct, it adds compatility for other mods.

It mostly adds new tool materials but other compatibility features are added as well.
'''

[[dependencies.materialis]]
    modId="forge"
    mandatory=true
    versionRange="[36,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.materialis]]
    modId="minecraft"
    mandatory=true
    versionRange="${minecraft_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.materialis]]
    modId="tconstruct"
    mandatory=true
    versionRange="${tconstruct_range}"
    ordering="NONE"
    side="BOTH"

[[dependencies.materialis]]
    modId="eidolon"
    mandatory=false
    versionRange="${eidolon_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.materialis]]
    modId="psi"
    mandatory=false
    versionRange="${psi_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.materialis]]
    modId="quark"
    mandatory=false
    versionRange="${quark_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.materialis]]
    modId="thermal"
    mandatory=false
    versionRange="${thermal_range}"
    ordering="AFTER"
    side="BOTH"

[[dependencies.materialis]]
    modId="create"
    mandatory=false
    versionRange="${create_range}"
    ordering="AFTER"
    side="BOTH"
